/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["arifle_MXC_khk_F","","acc_pointer_IR","optic_Holosight_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_AR_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_morphine",2],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_splint",3]]],["V_PlateCarrier2_tna_F",[["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["30Rnd_65x39_caseless_khaki_mag",6,30],["B_IR_Grenade",2,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17],["SmokeShell",3,1]]],["B_Mortar_01_weapon_F",[]],"H_HelmetB_Light_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "aa": {[["arifle_MXC_khk_F","","acc_pointer_IR","optic_Holosight_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],["launch_B_Titan_tna_F","","","",["Titan_AA",1],[],""],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_PlateCarrier1_tna_F",[["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_khaki_mag",8,30],["SmokeShell",5,1],["SmokeShellGreen",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_EntrenchingTool",1],["Titan_AA",3,1],["SmokeShell",2,1]]],"H_HelmetB_Light_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "at": {[["arifle_MXC_khk_F","","acc_pointer_IR","optic_Holosight_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],["launch_B_Titan_short_tna_F","","","",["Titan_AT",1],[],""],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_PlateCarrier1_tna_F",[["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_khaki_mag",8,30],["SmokeShell",5,1],["SmokeShellGreen",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_EntrenchingTool",1],["Titan_AT",3,1],["SmokeShell",2,1]]],"H_HelmetB_Light_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "autorifleman": {[["arifle_MX_SW_khk_F","","acc_pointer_IR","",["100Rnd_65x39_caseless_khaki_mag",100],[],"bipod_01_F_khk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_AR_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_PlateCarrier2_tna_F",[["100Rnd_65x39_caseless_khaki_mag",4,100],["HandGrenade",1,1],["SmokeShellGreen",1,1],["SmokeShell",3,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["100Rnd_65x39_caseless_khaki_mag",9,100],["ACE_SpareBarrel",1,1],["SmokeShell",5,1]]],"H_HelmetB_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "engineer": {[["arifle_MXC_khk_F","","acc_pointer_IR","optic_Holosight_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_SL_F",[["ACE_fieldDressing",10],["ACE_morphine",2],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_splint",3]]],["V_Chestrig_oli",[["30Rnd_65x39_caseless_khaki_mag",9,30],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ToolKit",1],["MineDetector",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["ACE_Clacker",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["SatchelCharge_Remote_Mag",1,1],["DemoCharge_Remote_Mag",4,1],["SmokeShell",4,1]]],"H_HelmetB_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "jtac": {[["arifle_MX_GL_khk_F","muzzle_snds_H_khk_F","acc_pointer_IR","optic_Hamr_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_P07_khk_F","muzzle_snds_L","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_PlateCarrier2_tna_F",[["30Rnd_65x39_caseless_khaki_mag",5,30],["MiniGrenade",2,1],["B_IR_Grenade",2,1],["1Rnd_HE_Grenade_shell",5,1],["SmokeShell",6,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["1Rnd_HE_Grenade_shell",20,1],["30Rnd_65x39_caseless_khaki_mag",10,30],["1Rnd_Smoke_Grenade_shell",10,1],["UGL_FlareGreen_Illumination_F",16,1]]],"H_Watchcap_khk","",["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "medic": {[["arifle_MX_khk_F","","acc_pointer_IR","",["30Rnd_65x39_caseless_khaki_mag",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_AR_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",2],["ACE_tourniquet",5],["ACE_epinephrine",2],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_splint",3]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_65x39_caseless_khaki_mag",8,30],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17],["SmokeShellGreen",1,1]]],["B_Carryall_oli",[["ACE_fieldDressing",20],["ACE_splint",10],["ACE_packingBandage",20],["ACE_elasticBandage",20],["ACE_quikclot",20],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_personalAidKit",10],["ACE_salineIV_500",10],["ACE_tourniquet",5],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["SmokeShell",10,1]]],"H_HelmetB_Light_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "pilot_cas_heli": {[["SMG_01_F","","","optic_Holosight_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],[],["U_B_HeliPilotCoveralls",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_TacVest_blk",[["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["30Rnd_45ACP_Mag_SMG_01",5,25],["SmokeShellGreen",1,1],["SmokeShell",1,1],["Chemlight_green",2,1]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "pilot_cas_plane": {[[],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_PilotCoveralls",[["ACE_tourniquet",5],["ACE_fieldDressing",10],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_WaterBottle",2],["ACE_splint",3]]],["V_Rangemaster_belt",[["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["16Rnd_9x21_Mag",3,17],["Chemlight_green",1,1],["SmokeShellOrange",1,1]]],[],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
    case "pilot_transport": {[["SMG_01_F","","","optic_Holosight_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],[],["U_B_HeliPilotCoveralls",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_splint",3]]],["V_TacVest_blk",[["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["30Rnd_45ACP_Mag_SMG_01",5,25],["SmokeShellGreen",1,1],["SmokeShell",1,1],["Chemlight_green",2,1]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "rifleman": {[["arifle_MX_khk_F","","acc_pointer_IR","optic_Hamr_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_Soldier_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",2],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_splint",3]]],["V_PlateCarrier1_tna_F",[["30Rnd_65x39_caseless_khaki_mag",9,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["HandGrenade",2,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_khaki_mag",8,30],["SmokeShell",6,1]]],"H_HelmetB_tna_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "sniper": {[["srifle_LRR_F","","","optic_LRPS",["7Rnd_408_Mag",7],[],""],[],["hgun_P07_khk_F","muzzle_snds_L","","",["16Rnd_9x21_Mag",17],[],""],["U_B_T_FullGhillie_tna_F",[["ACE_fieldDressing",10],["ACE_tourniquet",5],["ACE_morphine",2],["ACE_epinephrine",2],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_splint",3],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["SmokeShell",1,1]]],["V_PlateCarrier2_tna_F",[["ClaymoreDirectionalMine_Remote_Mag",1,1],["APERSTripMine_Wire_Mag",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",2,1],["SmokeShell",4,1],["7Rnd_408_Mag",4,7],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_oli",[["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["7Rnd_408_Mag",20,7],["SmokeShell",4,1]]],"","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    case "uav": {[["arifle_MX_khk_F","","acc_pointer_IR","optic_Hamr_khk_F",["30Rnd_65x39_caseless_khaki_mag",30],[],""],[],[],["U_B_T_Soldier_F",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",5],["ACE_morphine",2],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_splint",3]]],["V_PlateCarrierSpec_tna_F",[["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",2],["ACE_WaterBottle",2],["30Rnd_65x39_caseless_khaki_mag",5,30],["SmokeShell",2,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1]]],["B_UAV_01_backpack_F",[]],"H_HelmetB_tna_F","G_Combat_Goggles_tna_F",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
