/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["ef_arifle_mxar_coy_Holo_pointer","","EF_acc_pointer_IR_coy","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_4",[["FirstAidKit",2],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",2,30],["SmokeShell",1,1]]],["EF_V_AAV_Rifleman_Coy",[["FirstAidKit",4],["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["B_IR_Grenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",5,30]]],["EF_B_Mortar_01_weapon_MJTF_des",[]],"EF_H_MCH","G_Tactical_Black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "aa": {[["ef_arifle_mxar_coy_Hamr_pointer","","EF_acc_pointer_IR_coy","optic_Hamr",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],["launch_O_Titan_F","","","",["Titan_AA",1],[],""],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_1",[["FirstAidKit",5]]],["EF_V_AAV_Rifleman_Coy",[["FirstAidKit",4],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",8,30]]],["EF_B_Carryall_coy",[["FirstAidKit",2],["Titan_AA",3,1]]],"EF_H_MCH_BasicNet_Des","G_Combat",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "at": {[["ef_arifle_mxar_coy_Hamr_pointer","","EF_acc_pointer_IR_coy","optic_Hamr",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],["launch_O_Titan_short_F","","","",["Titan_AT",1],[],""],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_1",[["FirstAidKit",5]]],["EF_V_AAV_Rifleman_Coy",[["FirstAidKit",4],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",8,30]]],["EF_B_Carryall_coy",[["FirstAidKit",2],["Titan_AT",3,1]]],"EF_H_MCH_BasicNet_Des","G_Combat",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "autorifleman": {[["ef_arifle_mxar_coy","ef_snds_mxar_coy","EF_acc_pointer_IR_coy","ef_optic_mbs_remote_coy",["EF_100Rnd_65x39_caseless_coy_mag_Tracer",100],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_Support_Coy",[["16Rnd_9x21_Mag",2,16],["Chemlight_green",2,1],["EF_100Rnd_65x39_caseless_coy_mag_Tracer",4,100],["HandGrenade",1,1],["SmokeShellGreen",1,1],["SmokeShell",2,1]]],["EF_B_Carryall_coy",[["FirstAidKit",20],["SmokeShell",2,1],["EF_100Rnd_65x39_caseless_coy_mag_Tracer",6,100]]],"EF_H_MCH_BasicNet_Des","G_Combat",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "engineer": {[["ef_arifle_mxar_coy_Holo_pointer","","EF_acc_pointer_IR_coy","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_TL_Coy",[["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",1,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",9,30]]],["EF_B_Carryall_coy",[["ToolKit",1],["MineDetector",1],["FirstAidKit",12],["SatchelCharge_Remote_Mag",1,1],["DemoCharge_Remote_Mag",2,1],["SmokeShell",1,1]]],"EF_H_MCH_FullCamo_Des","G_Combat",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "jtac": {[["ef_arifle_MX_coy_MBS_pointer_snds","ef_snds_mxar_coy","EF_acc_pointer_IR_coy","ef_optic_mbs_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_4",[["FirstAidKit",5]]],["EF_V_AAV_TL_Coy",[["EF_30Rnd_65x39_caseless_coy_mag_Tracer",7,30],["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["B_IR_Grenade",2,1],["SmokeShell",2,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",1,1]]],["EF_B_Carryall_coy",[["FirstAidKit",30],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",8,30]]],"EF_H_MCH_FullCamo_Des","G_Tactical_Clear",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "medic": {[["ef_arifle_mxar_coy_Holo_pointer","","EF_acc_pointer_IR_coy","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_4",[["FirstAidKit",5]]],["EF_V_AAV_Support_Coy",[["16Rnd_9x21_Mag",2,16],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",10,30],["SmokeShell",3,1],["Chemlight_green",2,1]]],["EF_B_Carryall_coy",[["Medikit",1],["FirstAidKit",30]]],"EF_H_MCH_BasicNet_Des","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "pilot_cas_heli": {[["ef_arifle_mxc_coy_Holo","","","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_Coy",[["FirstAidKit",7],["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",4,30]]],[],"EF_H_HelmetCrew_Coy","G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "pilot_cas_plane": {[["ef_arifle_mxc_coy_Holo","","","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_Coy",[["FirstAidKit",7],["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",4,30]]],[],"EF_H_HelmetCrew_Coy","G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "pilot_transport": {[["ef_arifle_mxc_coy_Holo","","","ef_optic_Holosight_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_Coy",[["FirstAidKit",7],["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",4,30]]],[],"EF_H_HelmetCrew_Coy","G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "rifleman": {[["ef_arifle_mxar_coy_RCO_pointer_snds","ef_snds_mxar_coy","EF_acc_pointer_IR_coy","optic_Hamr",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_3",[["FirstAidKit",5]]],["EF_V_AAV_Rifleman_Coy",[["16Rnd_9x21_Mag",2,16],["SmokeShell",3,1],["SmokeShellGreen",1,1],["HandGrenade",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",9,30],["Chemlight_green",1,1]]],["EF_B_Carryall_coy",[["FirstAidKit",30],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",8,30]]],"EF_H_MCH_BasicNet_Des","G_Tactical_Clear",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "sniper": {[["ef_arifle_mxm_MBS_LP_BI","","EF_acc_pointer_IR_coy","ef_optic_mbs_remote_coy",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],"bipod_01_F_blk"],[],["ef_hgun_P07_coy","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_1",[["FirstAidKit",5]]],["EF_V_AAV_Scout_Coy",[["16Rnd_9x21_Mag",2,16],["HandGrenade",2,1],["SmokeShell",3,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",9,30]]],["EF_B_Carryall_coy",[["FirstAidKit",20]]],"EF_H_MCH_BasicNet_Coy","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    case "uav": {[["ef_arifle_mxar_coy_RCO_pointer_snds","ef_snds_mxar_coy","EF_acc_pointer_IR_coy","optic_Hamr",["EF_30Rnd_65x39_caseless_coy_mag_Tracer",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["EF_U_B_MarineCombatUniform_Des_5",[["FirstAidKit",5]]],["EF_V_AAV_TL_Coy",[["FirstAidKit",2],["16Rnd_9x21_Mag",2,16],["SmokeShellGreen",1,1],["HandGrenade",2,1],["EF_30Rnd_65x39_caseless_coy_mag_Tracer",8,30],["SmokeShell",2,1]]],["EF_B_UAV_01_backpack_coy",[]],"EF_H_MCH_BasicNet_Des","",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","EF_LPNVG_Tan"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
