/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["JCA_arifle_M4A4_AFG_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",6],["B_IR_Grenade",1,1],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_30Rnd_556x45_PMAG",7,30]]],["EF_B_CommandoMortar_weapon_MJTF_Wdl",[]],"E22_H_HelmetHBK_woodland_headset_F","E22_G_Glasses_Tactical_tinted_black_F",["Rangefinder","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "aa": {[["JCA_arifle_M4A1_short_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],["launch_B_Titan_olive_F","","JCA_acc_LaserModule_black_Pointer","",["Titan_AA",1],[],""],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",7],["HandGrenade",4,1],["SmokeShell",4,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["E22_B_HighCap_woodland",[["FirstAidKit",2],["JCA_30Rnd_556x45_PMAG",15,30],["Titan_AA",3,1]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "at": {[["JCA_arifle_M4A1_short_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],["launch_O_Titan_short_F","","JCA_acc_LaserModule_black_Pointer","",["Titan_AT",1],[],""],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",7],["HandGrenade",4,1],["SmokeShell",4,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["E22_B_HighCap_woodland",[["FirstAidKit",2],["DemoCharge_Remote_Mag",2,1],["Titan_AT",2,1],["Titan_AP",1,1],["JCA_30Rnd_556x45_PMAG",15,30]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "autorifleman": {[["LMG_Mk200_black_F","","JCA_acc_LaserModule_black_Pointer","JCA_optic_ACOG_black",["200Rnd_65x39_cased_Box_Tracer_Red",200],[],"JCA_bipod_04_black"],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",7],["HandGrenade",4,1],["SmokeShell",4,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],["E22_B_HighCap_woodland",[["FirstAidKit",7],["200Rnd_65x39_cased_Box_Tracer_Red",7,200]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "engineer": {[["JCA_arifle_M4A4_VFG_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",8],["SmokeShell",8,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["HandGrenade",2,1]]],["E22_B_Kitbag_woodland",[["ToolKit",1],["MineDetector",1],["FirstAidKit",4],["JCA_30Rnd_556x45_PMAG",18,30],["DemoCharge_Remote_Mag",2,1]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "jtac": {[["JCA_arifle_SR25_olive_F","JCA_muzzle_snds_762_tactical_olive","JCA_acc_DualMount_olive_Pointer","JCA_optic_HPCS_olive",["JCA_20Rnd_762x51_PMAG",20],[],"JCA_bipod_04_olive"],["JCA_launch_M72_olive_primed_F","","","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_recon_woodland_F",[["FirstAidKit",8],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["HandGrenade",3,1],["SmokeShell",4,1]]],["E22_B_Kitbag_woodland",[["FirstAidKit",10],["JCA_20Rnd_762x51_PMAG",20,20]]],"E22_H_HelmetHBK_woodland_headset_F","E22_G_Glasses_Tactical_tinted_black_F",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "medic": {[["JCA_arifle_M16A4_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],"JCA_bipod_04_olive"],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_combat_woodland_F",[["FirstAidKit",8],["SmokeShell",8,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["HandGrenade",2,1]]],["E22_B_Kitbag_woodland",[["Medikit",1],["FirstAidKit",20],["JCA_30Rnd_556x45_PMAG",15,30]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "pilot_cas_heli": {[["JCA_smg_UMP_olive_F","JCA_muzzle_snds_45_tactical_olive","","JCA_optic_ACOG_olive",["JCA_25Rnd_45ACP_UMP_Mag",25],[],""],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_Coveralls_olive_F",[["FirstAidKit",2],["JCA_17Rnd_9x21_P320_Mag",3,17],["SmokeShell",1,1]]],["JCA_V_CarrierRigKBT_01_compact_olive_F",[["FirstAidKit",7],["SmokeShell",2,1],["B_IR_Grenade",1,1],["JCA_SignalFlare_Green",2,1],["JCA_25Rnd_45ACP_UMP_Mag",4,25]]],[],"E22_H_Helmet_Heli_JTF_crew_woodland_F","E22_G_Shemagh_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "pilot_cas_plane": {[[],[],["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_Coveralls_grey_F",[["FirstAidKit",3],["JCA_17Rnd_9x21_P320_Mag",2,17],["SmokeShell",1,1]]],["JCA_V_CarrierRigKBT_01_compact_olive_F",[["FirstAidKit",6],["SmokeShell",2,1],["B_IR_Grenade",2,1],["JCA_SignalFlare_Green",2,1],["JCA_17Rnd_9x21_P320_Mag",7,17]]],[],"E22_H_Helmet_Fighter_JTF_F","E22_G_Shemagh_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
    case "pilot_transport": {[["JCA_smg_UMP_olive_F","JCA_muzzle_snds_45_tactical_olive","","JCA_optic_ACOG_olive",["JCA_25Rnd_45ACP_UMP_Mag",25],[],""],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_Coveralls_olive_F",[["FirstAidKit",2],["JCA_17Rnd_9x21_P320_Mag",3,17],["SmokeShell",1,1]]],["JCA_V_CarrierRigKBT_01_compact_olive_F",[["FirstAidKit",7],["SmokeShell",2,1],["B_IR_Grenade",1,1],["JCA_SignalFlare_Green",2,1],["JCA_25Rnd_45ACP_UMP_Mag",4,25]]],[],"E22_H_Helmet_Heli_JTF_crew_woodland_F","E22_G_Shemagh_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "rifleman": {[["JCA_arifle_M16A4_GL_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],["1Rnd_HE_Grenade_shell",1],""],["JCA_launch_M72_olive_primed_F","","","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["E22_V_CarrierRigKBT_01_heavy_woodland_F",[["FirstAidKit",7],["JCA_15Rnd_9x21_P226_Mag",4,15],["HandGrenade",2,1],["SmokeShell",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["UGL_FlareGreen_F",2,1]]],["E22_B_Kitbag_woodland",[["FirstAidKit",8],["JCA_30Rnd_556x45_PMAG",22,30],["1Rnd_HE_Grenade_shell",15,1],["1Rnd_Smoke_Grenade_shell",5,1]]],"E22_H_HelmetHBK_woodland_F","E22_G_Shemagh_light_Headset_woodland_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "sniper": {[["JCA_srifle_M107_olive_F","JCA_muzzle_snds_M107_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_HPPO_RAD_olive",["JCA_10Rnd_127x108_M107_Mag",10],[],"JCA_bipod_M107_olive"],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_FullGhillie_lsh",[["FirstAidKit",3],["JCA_17Rnd_9x21_P320_Mag",5,17]]],["E22_V_CarrierRigKBT_01_recon_woodland_F",[["FirstAidKit",9],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["HandGrenade",3,1],["SmokeShell",4,1]]],["E22_B_HighCap_woodland",[["FirstAidKit",5],["JCA_10Rnd_127x108_M107_Mag",12,10],["JCA_10Rnd_127x108_APDS_M107_Mag",4,10],["JCA_17Rnd_9x21_P320_Mag",3,17]]],"E22_H_HelmetHBK_woodland_F","G_Balaclava_TI_G_blk_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    case "uav": {[["JCA_arifle_M16A4_FG_olive_F","","JCA_acc_DualMount_olive_Pointer","JCA_optic_CRBS_olive",["JCA_30Rnd_556x45_PMAG",30],[],"JCA_bipod_04_olive"],[],["JCA_hgun_P320_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["E22_U_CombatUniform_woodland_F",[["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",3,17]]],["JCA_V_CarrierRigKBT_01_crew_olive_F",[["FirstAidKit",6],["SmokeShell",1,1],["JCA_30Rnd_556x45_PMAG",13,30]]],["E22_B_JTF_UAV_01_backpack_F",[]],"E22_H_HelmetHBK_woodland_headset_F","E22_G_Glasses_Tactical_tinted_black_F",["Rangefinder","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","E22_NVGoggles_woodland_F"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
