/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["arifle_MXC_F","","acc_pointer_IR","optic_Holosight",["30Rnd_65x39_caseless_mag",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier2_rgr",[["ACE_WaterBottle",3],["ACE_MRE_BeefStew",3],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_mag",5,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["16Rnd_9x21_Mag",2,17],["HandGrenade",2,1]]],["B_Mortar_01_weapon_F",[]],"H_HelmetB_light","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "aa": {[["arifle_MXC_F","","acc_pointer_IR","optic_Holosight",["30Rnd_65x39_caseless_mag",30],[],""],["launch_B_Titan_F","","","",["Titan_AA",1],[],""],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier1_rgr",[["30Rnd_65x39_caseless_mag",12,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_tourniquet",10],["ACE_splint",5],["ACE_fieldDressing",10],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["Titan_AA",2,1]]],"H_HelmetB_light_desert","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "at": {[["arifle_MXC_F","","acc_pointer_IR","optic_Holosight",["30Rnd_65x39_caseless_mag",30],[],""],["launch_B_Titan_short_F","","","",["Titan_AT",1],[],""],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier1_rgr",[["30Rnd_65x39_caseless_mag",12,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_tourniquet",10],["ACE_splint",5],["ACE_fieldDressing",10],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["Titan_AT",2,1]]],"H_HelmetB_light_desert","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "autorifleman": {[["arifle_MX_SW_F","","acc_pointer_IR","",["100Rnd_65x39_caseless_mag",100],[],"bipod_01_F_snd"],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["ACE_fieldDressing",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier2_rgr",[["100Rnd_65x39_caseless_mag",4,100],["HandGrenade",1,1],["SmokeShellGreen",1,1],["SmokeShell",3,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",10],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_splint",5],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["100Rnd_65x39_caseless_mag",7,100],["ACE_SpareBarrel",1,1]]],"H_HelmetB_grass","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "engineer": {[["arifle_MXC_F","","acc_pointer_IR","optic_Holosight",["30Rnd_65x39_caseless_mag",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_vest",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_Chestrig_rgr",[["30Rnd_65x39_caseless_mag",9,30],["HandGrenade",2,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ToolKit",1],["MineDetector",1],["ACE_fieldDressing",8],["ACE_packingBandage",8],["ACE_tourniquet",10],["ACE_WaterBottle",4],["ACE_MRE_BeefStew",4],["ACE_elasticBandage",8],["ACE_quikclot",8],["ACE_splint",5],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["SatchelCharge_Remote_Mag",1,1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetB_desert","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "jtac": {[["arifle_MX_GL_F","muzzle_snds_H","acc_pointer_IR","optic_Hamr",["30Rnd_65x39_caseless_mag",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_P07_snds_F","muzzle_snds_L","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier2_rgr",[["30Rnd_65x39_caseless_mag",5,30],["MiniGrenade",2,1],["B_IR_Grenade",2,1],["1Rnd_HE_Grenade_shell",5,1],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",1,1],["1Rnd_Smoke_Grenade_shell",2,1],["1Rnd_SmokeBlue_Grenade_shell",1,1],["1Rnd_SmokeGreen_Grenade_shell",1,1],["1Rnd_SmokeOrange_Grenade_shell",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",10],["ACE_splint",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_mag",15,30],["SmokeShell",5,1],["1Rnd_HE_Grenade_shell",10,1]]],"H_Watchcap_camo","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "medic": {[["arifle_MX_F","","acc_pointer_IR","",["30Rnd_65x39_caseless_mag",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam_tshirt",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_epinephrine",5],["ACE_quikclot",10]]],["V_PlateCarrierSpec_rgr",[["30Rnd_65x39_caseless_mag",7,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",1,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_tourniquet",20],["ACE_morphine",9],["ACE_fieldDressing",20],["ACE_elasticBandage",20],["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_splint",10],["ACE_personalAidKit",10],["ACE_epinephrine",9],["ACE_WaterBottle",5],["ACE_MRE_BeefStew",5],["ACE_salineIV_500",10],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1]]],"H_HelmetB_light_desert","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "pilot_cas_heli": {[["SMG_01_F","","","optic_Holosight_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],[],["U_B_HeliPilotCoveralls",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_TacVest_blk",[["ACE_MRE_BeefStew",3],["ACE_WaterBottle",3],["ACE_Flashlight_MX991",1],["ACE_tourniquet",5],["30Rnd_45ACP_Mag_SMG_01",4,25],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["SmokeShell",1,1],["Chemlight_green",2,1]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "pilot_cas_plane": {[[],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_PilotCoveralls",[["ACE_tourniquet",5],["ACE_quikclot",5],["ACE_packingBandage",5],["ACE_fieldDressing",5],["ACE_elasticBandage",5],["ACE_morphine",1],["ACE_epinephrine",1],["ACE_Flashlight_MX991",1],["ACE_MRE_BeefStew",1],["ACE_WaterBottle",1],["SmokeShellOrange",1,1],["Chemlight_green",2,1],["16Rnd_9x21_Mag",3,17]]],[],[],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
    case "pilot_transport": {[["SMG_01_F","","","optic_Holosight_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],[],["U_B_HeliPilotCoveralls",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_TacVest_blk",[["ACE_MRE_BeefStew",3],["ACE_WaterBottle",3],["ACE_Flashlight_MX991",1],["ACE_tourniquet",5],["30Rnd_45ACP_Mag_SMG_01",4,25],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["SmokeShell",1,1],["Chemlight_green",2,1]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "rifleman": {[["arifle_MX_F","","acc_pointer_IR","optic_Aco",["30Rnd_65x39_caseless_mag",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_CombatUniform_mcam",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_tourniquet",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5]]],["V_PlateCarrier1_rgr",[["30Rnd_65x39_caseless_mag",9,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["Chemlight_green",2,1],["HandGrenade",2,1],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_splint",5],["ACE_tourniquet",10],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_mag",8,30]]],"H_HelmetB","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "sniper": {[["srifle_LRR_camo_F","","","optic_LRPS",["7Rnd_408_Mag",7],[],""],[],["hgun_P07_snds_F","muzzle_snds_L","","",["16Rnd_9x21_Mag",16],[],""],["U_B_GhillieSuit",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_tourniquet",10],["ACE_morphine",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_epinephrine",5],["ACE_splint",5],["SmokeShell",1,1]]],["V_PlateCarrier2_rgr",[["ClaymoreDirectionalMine_Remote_Mag",1,1],["APERSTripMine_Wire_Mag",1,1],["SmokeShellGreen",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["Chemlight_green",2,1],["SmokeShell",4,1],["7Rnd_408_Mag",4,7],["16Rnd_9x21_Mag",2,17]]],["B_Carryall_cbr",[["ACE_fieldDressing",10],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",10],["ACE_MRE_BeefStew",5],["ACE_WaterBottle",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["7Rnd_408_Mag",15,7]]],"","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "uav": {[["arifle_MX_F","","acc_pointer_IR","optic_Aco",["30Rnd_65x39_caseless_mag",30],[],""],[],["hgun_P07_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_B_CombatUniform_mcam",[["ACE_fieldDressing",10],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_elasticBandage",10],["ACE_quikclot",10],["ACE_tourniquet",5],["ACE_epinephrine",5]]],["V_PlateCarrier2_rgr",[["ACE_MRE_BeefStew",3],["ACE_WaterBottle",3],["ACE_splint",5],["ACE_tourniquet",10],["ACE_EntrenchingTool",1],["ACE_Flashlight_MX991",1],["30Rnd_65x39_caseless_mag",5,30],["SmokeShell",1,1],["SmokeShellGreen",1,1],["16Rnd_9x21_Mag",2,17]]],["B_UAV_01_backpack_F",[]],"H_HelmetB","",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
