/*
Function: WHF_fnc_localChat

Description:
    Show a side chat message from a unit if they are near the player.

Parameters:
    Object unit:
        The unit that is chatting.
    String message:
        The message to show. May be a localizable key.
    Array params:
        (Optional, default [])
        The parameters to format the message with.

Author:
    thegamecracks

*/
params ["_unit", "_message", ["_params", []]];
if (focusOn distance _unit > 30) exitWith {};

_message = format ([_message call BIS_fnc_localize] + _params);
private _canSideChat =
    side group _unit isEqualTo side group focusOn
    && {assignedItems _unit findIf {
            getTextRaw (configFile >> "CfgWeapons" >> _x >> "simulation")
            isEqualTo "ItemRadio"
        } >= 0};

if (_canSideChat) then {_unit sideChat _message} else {_unit globalChat _message};

private _characterSounds = [
    ["a3\sounds_f\characters\human-sfx\p01\low_hit_01.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_02.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_03.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_04.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_05.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_06.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_1.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_2.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_3.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_4.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_5.wss","a3\sounds_f\characters\human-sfx\p01\low_hit_6.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_01.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_02.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_03.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_04.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_05.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_06.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_07.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_1.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_2.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_3.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_4.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_5.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_6.wss","a3\sounds_f\characters\human-sfx\p01\max_hit_7.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_01.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_02.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_03.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_04.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_1.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_2.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_3.wss","a3\sounds_f\characters\human-sfx\p01\mid_hit_4.wss"],
    ["a3\sounds_f\characters\human-sfx\p02\low_hit_01.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_02.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_03.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_04.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_05.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_06.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_1.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_2.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_3.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_4.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_5.wss","a3\sounds_f\characters\human-sfx\p02\low_hit_6.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_01.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_02.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_03.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_04.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_1.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_2.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_3.wss","a3\sounds_f\characters\human-sfx\p02\max_hit_4.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_01.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_02.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_03.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_04.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_1.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_2.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_3.wss","a3\sounds_f\characters\human-sfx\p02\mid_hit_4.wss"],
    ["a3\sounds_f\characters\human-sfx\p03\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p03\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p03\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p03\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p03\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p03\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p03\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p03\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p03\hit_mid_3.wss"],
    ["a3\sounds_f\characters\human-sfx\p04\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p04\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p04\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p04\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p04\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p04\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p04\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p04\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p04\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p04\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p04\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p04\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p04\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p04\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p04\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p05\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p05\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p05\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p05\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p05\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p05\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p05\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p05\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p05\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p05\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p05\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p05\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p05\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p05\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p05\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p06\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p06\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p06\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p06\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p06\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p06\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p06\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p06\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p06\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p06\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p06\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p06\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p06\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p06\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p06\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p07\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p07\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p07\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p07\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p07\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p07\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p07\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p07\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p07\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p07\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p07\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p07\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p07\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p07\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p07\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p08\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p08\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p08\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p08\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p08\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p08\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p08\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p08\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p08\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p08\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p08\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p08\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p08\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p08\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p08\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p09\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p09\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p09\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p09\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p09\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p09\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p09\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p09\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p09\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p09\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p09\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p09\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p09\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p09\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p09\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p10\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p10\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p10\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p10\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p10\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p10\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p10\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p10\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p10\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p10\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p10\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p10\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p10\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p10\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p10\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p11\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p11\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p11\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p11\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p11\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p11\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p11\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p11\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p11\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p11\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p11\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p11\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p11\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p11\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p11\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p12\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p12\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p12\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p12\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p12\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p12\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p12\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p12\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p12\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p12\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p12\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p12\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p12\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p12\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p12\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p13\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p13\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p13\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p13\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p13\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p13\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p13\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p13\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p13\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p13\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p13\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p13\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p13\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p13\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p13\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p14\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p14\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p14\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p14\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p14\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p14\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p14\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p14\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p14\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p14\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p14\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p14\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p14\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p14\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p14\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p15\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p15\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p15\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p15\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p15\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p15\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p15\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p15\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p15\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p15\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p15\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p15\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p15\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p15\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p15\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p16\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p16\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p16\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p16\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p16\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p16\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p16\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p16\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p16\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p16\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p16\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p16\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p16\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p16\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p16\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p17\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p17\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p17\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p17\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p17\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p17\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p17\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p17\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p17\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p17\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p17\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p17\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p17\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p17\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p17\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\p18\hit_low_1.wss","a3\sounds_f\characters\human-sfx\p18\hit_low_2.wss","a3\sounds_f\characters\human-sfx\p18\hit_low_3.wss","a3\sounds_f\characters\human-sfx\p18\hit_low_4.wss","a3\sounds_f\characters\human-sfx\p18\hit_low_5.wss","a3\sounds_f\characters\human-sfx\p18\hit_max_1.wss","a3\sounds_f\characters\human-sfx\p18\hit_max_2.wss","a3\sounds_f\characters\human-sfx\p18\hit_max_3.wss","a3\sounds_f\characters\human-sfx\p18\hit_max_4.wss","a3\sounds_f\characters\human-sfx\p18\hit_max_5.wss","a3\sounds_f\characters\human-sfx\p18\hit_mid_1.wss","a3\sounds_f\characters\human-sfx\p18\hit_mid_2.wss","a3\sounds_f\characters\human-sfx\p18\hit_mid_3.wss","a3\sounds_f\characters\human-sfx\p18\hit_mid_4.wss","a3\sounds_f\characters\human-sfx\p18\hit_mid_5.wss"],
    ["a3\sounds_f\characters\human-sfx\person0\p0_hit_01.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_02.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_03.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_04.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_05.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_06.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_07.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_08.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_09.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_10.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_11.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_12.wss","a3\sounds_f\characters\human-sfx\person0\p0_hit_13.wss"],
    ["a3\sounds_f\characters\human-sfx\person1\p1_hit_01.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_02.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_03.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_04.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_05.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_06.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_07.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_08.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_09.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_10.wss","a3\sounds_f\characters\human-sfx\person1\p1_hit_11.wss"],
    ["a3\sounds_f\characters\human-sfx\person2\p2_hit_01.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_02.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_03.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_04.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_05.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_06.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_07.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_08.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_09.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_small_01.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_small_02.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_small_03.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_small_04.wss","a3\sounds_f\characters\human-sfx\person2\p2_hit_small_05.wss"],
    ["a3\sounds_f\characters\human-sfx\person3\p3_hit_01.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_02.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_03.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_04.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_05.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_06.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_07.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_08.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_09.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_10.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_11.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_12.wss","a3\sounds_f\characters\human-sfx\person3\p3_hit_13.wss"]
];
private _seed = parseNumber (netId _unit splitString ":" select 1);
private _index = floor (_seed random count _characterSounds + 1 % count _characterSounds);
private _sound = selectRandom (_characterSounds # _index);

if (_unit isEqualTo focusOn) then {
    playSoundUI [_sound, 4, 1, true];
} else {
    playSound3D [
        _sound,
        _unit,
        false,
        _unit modelToWorldVisual (_unit selectionPosition "Head"),
        5,
        1,
        0,
        0,
        true
    ];
};
