/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["JCA_smg_UMP_AFG_olive_F","JCA_muzzle_snds_45_tactical_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_25Rnd_45ACP_UMP_Mag",25],[],""],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_17Rnd_9x21_P320_Mag",3,17],["Chemlight_green",1,1]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1]]],["B_AssaultPack_wdl_F",[["FirstAidKit",1],["Laserbatteries",2,1],["JCA_25Rnd_45ACP_UMP_Mag",12,25],["SmokeShell",2,1],["Chemlight_green",2,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "aa": {[["JCA_arifle_HK433_short_olive_F","muzzle_snds_M","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],["launch_B_Titan_olive_F","","JCA_acc_LaserModule_black_Pointer","",["Titan_AA",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_15Rnd_9x21_P226_Mag",3,15]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["JCA_30Rnd_556x45_PMAG",1,30]]],["B_Carryall_green_F",[["FirstAidKit",1],["JCA_30Rnd_556x45_PMAG",18,30],["Titan_AA",2,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "at": {[["JCA_arifle_HK433_short_olive_F","muzzle_snds_M","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],""],["launch_O_Titan_short_F","","JCA_acc_LaserModule_black_Pointer","",["Titan_AT",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_15Rnd_9x21_P226_Mag",3,15]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["JCA_30Rnd_556x45_PMAG",1,30]]],["B_Carryall_green_F",[["FirstAidKit",1],["Titan_AT",2,1],["JCA_30Rnd_556x45_PMAG",18,30]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "autorifleman": {[["LMG_03_F","muzzle_snds_M","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["200Rnd_556x45_Box_F",200],[],""],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_15Rnd_9x21_P226_Mag",3,15]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1]]],["B_Carryall_green_F",[["200Rnd_556x45_Box_Red_F",8,200]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "engineer": {[["JCA_arifle_HK433_short_olive_F","muzzle_snds_M","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],"JCA_bipod_04_olive"],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["Chemlight_green",3,1]]],["B_Carryall_green_F",[["ToolKit",1],["DemoCharge_Remote_Mag",1,1],["SmokeShell",3,1],["JCA_30Rnd_556x45_PMAG",20,30],["SatchelCharge_Remote_Mag",1,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "jtac": {[["JCA_arifle_SR25_olive_F","JCA_muzzle_snds_762_tactical_black","JCA_acc_LaserModule_black_Pointer","JCA_optic_HPCS_olive",["JCA_20Rnd_762x51_SMAG",20],[],"JCA_bipod_04_olive"],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_17Rnd_9x21_P320_Mag",3,17],["Chemlight_green",1,1]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1]]],["B_Carryall_green_F",[["FirstAidKit",1],["JCA_20Rnd_762x51_PMAG",20,20],["Laserbatteries",2,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Laserdesignator_03","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "medic": {[["JCA_arifle_HK433_olive_F","muzzle_snds_M","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_PMAG",30],[],"JCA_bipod_04_olive"],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["JCA_30Rnd_556x45_PMAG",1,30]]],["B_Carryall_green_F",[["FirstAidKit",25],["SmokeShell",3,1],["JCA_30Rnd_556x45_PMAG",18,30]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "pilot_cas_heli": {[["JCA_smg_MP5_VFG_olive_F","JCA_muzzle_snds_9MM_tactical_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_9x21_MP5_Mag",30],[],""],[],["JCA_hgun_P226_olive_F","","JCA_acc_LightMount_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_HeliPilotCoveralls",[["MineDetector",1],["Chemlight_green",1,1],["JCA_15Rnd_9x21_P226_Mag",3,15]]],["V_TacVestIR_blk",[["FirstAidKit",4],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["B_IR_Grenade",2,1],["JCA_30Rnd_9x21_MP5_Mag",5,30]]],[],"H_PilotHelmetHeli_B","JCA_G_shemagh_01_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "pilot_cas_plane": {[["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","JCA_acc_LightMount_Pistol_olive","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_PilotCoveralls",[["MineDetector",1],["FirstAidKit",4],["JCA_17Rnd_9x21_P320_Mag",1,17]]],["V_Rangemaster_belt",[["JCA_17Rnd_9x21_P320_Mag",6,17]]],["B_LegStrapBag_black_F",[["SmokeShell",4,1],["JCA_SignalFlare_Green",2,1],["B_IR_Grenade",2,1],["Chemlight_green",4,1],["HandGrenade",2,1]]],"H_PilotHelmetFighter_B","JCA_G_shemagh_01_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
    case "pilot_transport": {[["JCA_smg_MP5_VFG_olive_F","JCA_muzzle_snds_9MM_tactical_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_9x21_MP5_Mag",30],[],""],[],["JCA_hgun_P226_olive_F","","JCA_acc_LightMount_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_HeliPilotCoveralls",[["MineDetector",1],["Chemlight_green",1,1],["JCA_15Rnd_9x21_P226_Mag",3,15]]],["V_TacVestIR_blk",[["FirstAidKit",4],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["B_IR_Grenade",2,1],["JCA_30Rnd_9x21_MP5_Mag",5,30]]],[],"H_PilotHelmetHeli_B","JCA_G_shemagh_01_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "rifleman": {[["JCA_arifle_M4A4_GL_olive_F","JCA_muzzle_snds_556_Enhanced_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_30Rnd_556x45_Green_PMAG",30],["1Rnd_HE_Grenade_shell",1],""],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P226_olive_F","","JCA_acc_LightModule_Pistol_olive","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["1Rnd_HE_Grenade_shell",3,1],["JCA_15Rnd_9x21_P226_Mag",1,15]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",8],["SmokeShell",2,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1],["1Rnd_HE_Grenade_shell",7,1]]],["B_Carryall_green_F",[["FirstAidKit",4],["JCA_30Rnd_556x45_PMAG",20,30],["1Rnd_Smoke_Grenade_shell",6,1],["UGL_FlareGreen_F",4,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "sniper": {[["JCA_srifle_AWM_olive_F","JCA_muzzle_snds_AWM_olive","","JCA_optic_HPCS_olive",["JCA_5Rnd_338LM_AWM_Mag",5],[],"JCA_bipod_AWM_01_black"],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_FullGhillie_lsh",[["MineDetector",1],["Chemlight_green",1,1],["JCA_17Rnd_9x21_P320_Mag",6,17]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1]]],["B_Carryall_green_F",[["DemoCharge_Remote_Mag",2,1],["SmokeShell",3,1],["JCA_5Rnd_338LM_AWM_Mag",26,5]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    case "uav": {[["JCA_smg_UMP_AFG_olive_F","JCA_muzzle_snds_45_tactical_olive","JCA_acc_LaserModule_olive_Pointer","JCA_optic_ACOG_olive",["JCA_25Rnd_45ACP_UMP_Mag",25],[],""],["JCA_launch_M72_olive_primed_F","","JCA_acc_LaserModule_olive_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P320_olive_F","JCA_muzzle_snds_9MM_enhanced_olive","","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Mag",17],[],""],["U_B_CombatUniform_mcam_wdl_f",[["MineDetector",1],["JCA_17Rnd_9x21_P320_Mag",3,17],["Chemlight_green",1,1]]],["JCA_V_CarrierRigKBT_01_combat_olive_F",[["FirstAidKit",11],["SmokeShell",3,1],["HandGrenade",2,1],["JCA_SignalFlare_Green",1,1]]],["B_AssaultPack_wdl_F",[["FirstAidKit",1],["Laserbatteries",2,1],["JCA_25Rnd_45ACP_UMP_Mag",12,25],["SmokeShell",2,1],["Chemlight_green",2,1]]],"H_HelmetB_plain_wdl","JCA_G_shemagh_01_headset_glasses_olive_F",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
