/*
Function: WHF_fnc_getLastLoadout

Description:
    Get the player's last loadout.
    If no last loadout could be found, an empty array is returned.

Parameters:
    String role:
        (Optional, default player getVariable ["WHF_role", ""])
        The role to get the player's last loadout for.
    String collection:
        (Optional, default WHF_loadout_collection)
        The loadout collection to retrieve the player's last loadout from.
        Use "" or "default" to retrieve the default loadout.

Returns:
    Array

Author:
    thegamecracks

*/
params [["_role", player getVariable ["WHF_role", ""]], ["_collection", WHF_loadout_collection]];
if (_role isEqualTo "") exitWith {[]};

private _loadouts = missionProfileNamespace getVariable ["WHF_last_loadouts", createHashMap];
private _key = [_collection, _role];
private _loadout = _loadouts getOrDefaultCall [_key, {switch (_role) do {
    case "arty": {[["JCA_arifle_HK437_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_MROS_sand",["JCA_30Rnd_300BLK_Tracer_Red_sand_EMAG",30],[],""],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_CQB_sand_F",[["FirstAidKit",5],["SmokeShell",4,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["JCA_30Rnd_300BLK_Tracer_Red_sand_EMAG",9,30]]],["B_Mortar_01_weapon_F",[]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "aa": {[["JCA_arifle_M4A4_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",30],[],""],["launch_B_Titan_F","","JCA_acc_LaserModule_sand_Pointer","",["Titan_AA",1],[],""],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",13,30]]],["WHB_B_Carryall_cbr",[["FirstAidKit",30],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",10,30],["Titan_AA",7,1]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "at": {[["JCA_arifle_M4A4_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",30],[],""],["launch_B_Titan_short_F","","JCA_acc_LaserModule_sand_Pointer","",["Titan_AT",1],[],""],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",13,30]]],["WHB_B_Carryall_cbr",[["FirstAidKit",30],["Titan_AT",7,1],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",10,30]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "autorifleman": {[["MMG_02_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["130Rnd_338_Mag",130],[],"JCA_bipod_04_sand"],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",6,15],["Chemlight_green",1,1],["130Rnd_338_Mag",1,130]]],["WHB_B_Carryall_cbr",[["FirstAidKit",30],["HandGrenade",2,1],["130Rnd_338_Mag",12,130]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "engineer": {[["JCA_arifle_HK437_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_MROS_sand",["JCA_30Rnd_300BLK_Tracer_Red_sand_EMAG",30],[],""],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_CQB_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",4,15],["Chemlight_green",1,1],["JCA_30Rnd_300BLK_Tracer_Red_sand_EMAG",12,30]]],["B_Carryall_cbr",[["FirstAidKit",20],["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",3,1]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "jtac": {[["JCA_arifle_M16A4_GL_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",30],["1Rnd_HE_Grenade_shell",1],""],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",13,30]]],["WHB_B_AssaultPack_cbr",[["FirstAidKit",25],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",6,30],["GX_1RND_DRONE40_HE_M203",5,100],["1Rnd_HE_Grenade_shell",20,1],["1Rnd_SmokeOrange_Grenade_shell",6,1]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "medic": {[["JCA_arifle_SR10_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_20Rnd_762x51_Tracer_Red_Sand_PMAG",20],[],""],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",4,15],["Chemlight_green",1,1],["JCA_20Rnd_762x51_Tracer_Red_Sand_PMAG",7,20]]],["WHB_B_AssaultPack_cbr",[["FirstAidKit",40],["Medikit",1],["JCA_20Rnd_762x51_Tracer_Red_Sand_PMAG",6,20]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "pilot_cas_heli": {[["JCA_smg_MP5_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_ARO_sand",["JCA_30Rnd_9x21_MP5_Tracer_Red_Sand_Mag",30],[],""],[],[],["U_B_HeliPilotCoveralls",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_recon_sand_F",[["FirstAidKit",5],["SmokeShell",4,1],["Chemlight_green",2,1],["JCA_30Rnd_9x21_MP5_Tracer_Red_Sand_Mag",7,30]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "pilot_cas_plane": {[[],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_PilotCoveralls",[["FirstAidKit",4],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["SmokeShell",2,1]]],["V_BandollierB_cbr",[["FirstAidKit",6],["JCA_15Rnd_9x21_P226_Mag",4,15],["SmokeShell",2,1]]],[],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
    case "pilot_transport": {[["JCA_smg_MP5_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_ARO_sand",["JCA_30Rnd_9x21_MP5_Tracer_Red_Sand_Mag",30],[],""],[],[],["U_B_HeliPilotCoveralls",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_recon_sand_F",[["FirstAidKit",5],["SmokeShell",4,1],["Chemlight_green",2,1],["JCA_30Rnd_9x21_MP5_Tracer_Red_Sand_Mag",7,30]]],[],"H_PilotHelmetHeli_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "rifleman": {[["JCA_arifle_HK433_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_30Rnd_556x45_Tracer_Red_sand_EMAG",30],[],""],["JCA_launch_M72_sand_primed_F","","JCA_acc_LaserModule_sand_Pointer","",["JCA_M72_HEAT_F",1],[],""],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["JCA_30Rnd_556x45_Tracer_Red_sand_EMAG",13,30],["Chemlight_green",1,1]]],["B_Carryall_cbr",[["FirstAidKit",30],["JCA_30Rnd_556x45_Tracer_Red_sand_EMAG",10,30],["HandGrenade",2,1]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "sniper": {[["JCA_srifle_AWM_sand_F","JCA_muzzle_snds_AWM_sand","","JCA_optic_MRPS_sand",["JCA_5Rnd_338LM_AWM_Mag",5],[],"JCA_bipod_AWM_02_black"],[],["JCA_hgun_P226_sand_F","JCA_muzzle_snds_9MM_tactical_sand","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_FullGhillie_ard",[["FirstAidKit",7]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["SmokeShell",3,1],["HandGrenade",2,1],["JCA_15Rnd_9x21_P226_Mag",4,15],["Chemlight_green",1,1],["JCA_5Rnd_338LM_AWM_Tracer_Red_Mag",7,5]]],["B_Carryall_cbr",[["FirstAidKit",23],["JCA_5Rnd_338LM_AWM_Tracer_Red_Mag",13,5]]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    case "uav": {[["JCA_arifle_M4A4_VFG_sand_F","","JCA_acc_LaserModule_sand_Pointer","JCA_optic_CRBS_sand",["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",30],[],""],[],["JCA_hgun_P226_sand_F","","JCA_acc_LightModule_Pistol_sand","JCA_optic_MPO_black",["JCA_15Rnd_9x21_P226_Mag",15],[],""],["U_B_CombatUniform_mcam",[["FirstAidKit",5]]],["JCA_V_CarrierRigKBT_01_combat_sand_F",[["FirstAidKit",5],["SmokeShell",2,1],["JCA_15Rnd_9x21_P226_Mag",3,15],["Chemlight_green",1,1],["JCA_30Rnd_556x45_Tracer_Red_sand_PMAG",10,30]]],["B_UAV_01_backpack_F",[]],"JCA_H_HelmetHBK_headset_sand_F","JCA_G_shemagh_01_headset_glasses_sand_F",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","ItemRadio","ItemCompass","ItemWatch","NVGoggles"]]};
    default {[]};
}}];
[_loadout] call WHF_fnc_filterUnitLoadout
